# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    assignees:
      - Ayc0
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: sharp # needs to follow Astro's optionalDependency version
      - dependency-name: react
        versions: [18.3.1] # pinned to this version on purpose
      - dependency-name: react-dom
        versions: [18.3.1] # pinned to this version on purpose

  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - Ayc0
    schedule:
      interval: "weekly"
