nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
    - current
  libc:
    - glibc
  os:
    - darwin
    - linux
    - current

yarnPath: .yarn/releases/yarn-4.5.1.cjs
# packageExtensions:
#   react-dom@18.3.1:
#     dependencies:
#       react: "18.3.1"
